require("plugins")

require("settings.options")
require("settings.colorscheme")
require("settings.keymaps")

require("plugins.lualine")
require("plugins.bufferline")
require("plugins.nvim-tree")
require("plugins.telescope")
require("plugins.nvim-cmp")
require("plugins.gitsigns")
require("plugins.nvim-autopairs")
require("plugins.treesitter")
require("plugins.comment")
require("plugins.csv-tools")
require("plugins.indent-blankline")

require("lsp.mason")
require("lsp.lspsaga")
require("lsp.lspconfig")
require("lsp.null-ls")
